### ISSUE TITLE
Demo Account and OutgoingCallerID support

### ISSUE THREAD

**Issue by tmzt** [ukd1/node-twilio#1]
Demo accounts (free credit on twilio.com) are not allocated OutgoingNumbers, so client.getPhoneNumber() fails even though there are numbers registered which work for outgoing calls with the REST api, this also means that the registration of incoming events not associated with outgoing calls is automatic which may not be desired.

Proposed fix: add a getOutgoingNumber() call to match getPhoneNumber() which does not register the incoming number callbacks, other wise the API would be unchanged.  This may require an additional parameter to the PhoneNumber constructor which is an internal object and not exported.

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
