### ISSUE TITLE
Is there mandatory events with incomingCall?

### ISSUE THREAD

**Issue by yevgenko** [ukd1/node-twilio#16]
After every "incomingCall" event the twilio debugger gets populated with the following error:

```
ERROR HTTP connection failure

An attempt to retrieve TwiML from
http://4iif.localtunnel.com/autoprovision/3
failed; the connection timed out. Please check the URL and your network settings and try again.
```

And according to **Request** it looks like a call status data
I'm wondering which event I should listen to to omit this error?

e.g. for outgoing call I must be listening to "ended" even to omit another similar issue, but it didn't help with incomingCall event...

Thanks.

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
