### ISSUE TITLE
Modules object is deprecated

### ISSUE THREAD

**Issue by garrettwilkin** [ukd1/node-twilio#17]
Hello,

I've just attempted to install the package with npm and I got the warning about 'modules' being deprecated.  I think there's a new way of doing this in the later versions of node, and so the code has to be refactored slightly.

The version of node I'm running is the latest: 'v0.7.0-pre'

npm install twilio
npm http GET https://registry.npmjs.org/twilio
npm http 200 https://registry.npmjs.org/twilio
npm http GET https://registry.npmjs.org/twilio/-/twilio-0.4.0.tgz
npm http 200 https://registry.npmjs.org/twilio/-/twilio-0.4.0.tgz
npm WARN twilio@0.4.0 package.json: **'modules' object is deprecated**
twilio@0.4.0 ./node_modules/twilio 

I'm looking forward to giving this module a try!

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
