### ISSUE TITLE
Use on dev machines.

### ISSUE THREAD

**Issue by jkarmel** [ukd1/node-twilio#18]
Hey, this is my first twillio app ever and I am a newcomer to node as well so please forgive my ignorance. I'm trying to use the dial-list example you provided to create the application. 

I keep on getting the following error:

```
 Error: Could not get number +NNNNNNNNNN
```

I just tried to do the demo app after verifying my personal number on the twillio website. I used that number for the outgoing number in the config file. I'm confused about what I should put for the hostname. I tried to use my IP address but that didn't work. I would like to try things from my dev machine, rather than push to heroku or ec2 to see if things are working. Any advice?

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
