### ISSUE TITLE
Dial Syntax?

### ISSUE THREAD

**Issue by nickmerwin** [ukd1/node-twilio#21]
I'm trying to get it to just forward the call -- not sure what I'm doing wrong here:

``` javascript


phone.setup(function() {
  phone.on('incomingCall', function(reqParams, res) {
    console.log("New Call:");

    var dial = new Twiml.Dial({Number: new Twiml.Num("+15555555"), callerId: "+15555555"});

    res.append(dial);
    res.send();
  });
});

```

Twilio is saying app error but I'm not seeing anything in my logs -- perhaps a timeout. Do I need to listen for the answered event or am I just getting the Twiml API wrong?

Thanks!

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
