### ISSUE TITLE
Changing "hostname" to "base_url"

### ISSUE THREAD

**Issue by robertjd** [ukd1/node-twilio#23]
I was needing more flexibility for specifying the protocol (http/https) and port (80/443) for the callback URI, so I simplified the whole process by just passing an entire URL string into lib/auto-uri.js

I updated the rest of the project accordingly.  See this commit in my fork:

https://github.com/robertjd/node-twilio/commit/ce0a9f2e78a627fba0371c4cc1e056e3be63f6cb

I wanted to solicit opinions on this before I make a pull request.

Thanks everyone!

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
