### ISSUE TITLE
Facilitate Paging?

### ISSUE THREAD

**Issue by langdonx** [ukd1/node-twilio#29]
I don't see any way to get the next set of data with the twilioClient object.  I'm calling getIncomingNumbers and have quite a few to pull down.  I suppose I could just say:

```
client.getIncomingNumbers({ 'PageSize': 150 }, function(data) { .. });
```

But that doesn't really seem future proof.

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
