### ISSUE TITLE
Library incompatible with Heroku, etc

### ISSUE THREAD

**Issue by clintandrewhall** [ukd1/node-twilio#7]
This library is incompatible with hosting platforms like Heroku and Joyent, which provide you with a specific port in which to listen.  The AutoUri lib makes it necessary to have an additional port open for Twilio requests.  Apps therefore crash on startup.

Can the library accept an existing express instance, and add endpoints to it?

**Comment by ukd1** [comment]
This library is deprecated in favor of the official library - https://github.com/twilio/twilio-node
